import * as fse from "fs-extra"
import * as os from "os"
import { resolve } from "path"
import { getComponentName } from "./get-icon-data"

const AUTO_GENERATED_WARN =
  `
/**
 * This file is automatically generated.
 * Please do not change this file!
 */
` + os.EOL

export async function generateDomainIndex(path: string) {
  let index = AUTO_GENERATED_WARN

  const files = await fse.readdir(path)

  files
    .filter((f) => f !== "index.ts")
    .forEach((file) => {
      const name = file.replace(".tsx", "")
      const componentName = getComponentName(name)

      index +=
        `export { default as ${componentName} } from "./${name}";` + os.EOL
    })

  await fse.writeFile(resolve(path, "index.ts"), index)
}

export async function generateRootIndex(path: string) {
  let index = AUTO_GENERATED_WARN

  const entries = await fse.readdir(path)

  entries
    .filter((f) => f !== "index.ts")
    .forEach((e) => {
      index += `export * from "./${e}";` + os.EOL
    })

  await fse.writeFile(resolve(path, "index.ts"), index)
}
