/**
 * This file was generated automatically by the @perseus/generate-icons CLI.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../../types";
const ArrowUpRightOnBox = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      d="M9.054 5.327H4.743A1.752 1.752 0 0 0 2.99 7.079v8.178a1.752 1.752 0 0 0 1.753 1.753h8.178a1.752 1.752 0 0 0 1.752-1.753v-4.236m-7.67 1.993L17.01 2.99m0 0h-4.09m4.09 0v4.09"
      stroke={color}
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);
const ForwardRef = forwardRef(ArrowUpRightOnBox);
export default ForwardRef;
