/**
 * This file was generated automatically by @medusa-ui/cli.
 * Do not edit this file directly.
 */
import * as React from "react"
import { Ref, forwardRef } from "react"
import type { IconProps } from "../../types"
const ArrowRightOnRectangle = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>,
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      d="M13.125 7.5V4.375A1.875 1.875 0 0 0 11.25 2.5h-5a1.875 1.875 0 0 0-1.875 1.875v11.25A1.875 1.875 0 0 0 6.25 17.5h5a1.875 1.875 0 0 0 1.875-1.875V12.5m2.5 0 2.5-2.5m0 0-2.5-2.5m2.5 2.5H7.5"
      stroke={color}
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)
const ForwardRef = forwardRef(ArrowRightOnRectangle)
export default ForwardRef
