/**
 * This file was generated automatically by @medusa-ui/cli.
 * Do not edit this file directly.
 */
import * as React from "react"
import { Ref, forwardRef } from "react"
import type { IconProps } from "../../types"
const BuildingTax = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>,
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      d="M17.5 7.5h-15V5.833L10 2.5l7.5 3.333V7.5Z"
      stroke={color}
      strokeWidth={1.5}
      strokeLinejoin="round"
    />
    <path
      d="M8.333 16.667H2.5l.73-2.5h5.103"
      stroke={color}
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path d="M4.167 7.5v6.667m3.333 0V7.5" stroke={color} strokeWidth={1.5} />
    <path
      d="m17.135 11.198-5.104 5.104M12.292 12.083a.625.625 0 1 0 0-1.25.625.625 0 0 0 0 1.25ZM16.875 16.667a.625.625 0 1 0 0-1.25.625.625 0 0 0 0 1.25Z"
      stroke={color}
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
)
const ForwardRef = forwardRef(BuildingTax)
export default ForwardRef
