/**
 * This file was generated automatically by @medusa-ui/cli.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../../types";
const ClockSolidMini = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M4 10a6 6 0 1 1 12 0 6 6 0 0 1-12 0Zm6-4.25a.75.75 0 0 1 .75.75v3.13l2.441.645a.75.75 0 0 1-.382 1.45l-3-.792a.75.75 0 0 1-.559-.725V6.5a.75.75 0 0 1 .75-.75Z"
      fill={color}
    />
  </svg>
);
const ForwardRef = forwardRef(ClockSolidMini);
export default ForwardRef;
