/**
 * This file was generated automatically by @medusa-ui/cli.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../../types";
const ClockSolid = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M1.75 10a8.25 8.25 0 1 1 16.5 0 8.25 8.25 0 0 1-16.5 0ZM10 5.083a.75.75 0 0 1 .75.75v3.944l2.128 1.242a.75.75 0 1 1-.756 1.295l-2.5-1.458a.75.75 0 0 1-.372-.648V5.833a.75.75 0 0 1 .75-.75Z"
      fill={color}
    />
  </svg>
);
const ForwardRef = forwardRef(ClockSolid);
export default ForwardRef;
