/**
 * This file was generated automatically by the @medusa-ui/generate-icons CLI.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../../types";
const CommandLineSolid = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M3.636 3.4a2.121 2.121 0 0 0-2.121 2.122v8.956A2.121 2.121 0 0 0 3.636 16.6h12.728a2.122 2.122 0 0 0 2.121-2.12V5.521A2.121 2.121 0 0 0 16.364 3.4H3.636Zm.89 8.252a.707.707 0 0 1 .051-1L6.35 9.057 4.577 7.461a.707.707 0 1 1 .947-1.05L7.88 8.532a.707.707 0 0 1 0 1.05l-2.357 2.122a.707.707 0 0 1-.999-.052Zm5.238-1.416a.707.707 0 0 0 0 1.414h2.357a.707.707 0 0 0 0-1.414H9.764Z"
      fill={color}
    />
  </svg>
);
const ForwardRef = forwardRef(CommandLineSolid);
export default ForwardRef;
