/**
 * This file was generated automatically by @medusa-ui/cli.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../../types";
const ComponentSolid = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      d="M5.125 7.375 7.75 10l-2.625 2.625L2.5 10l2.625-2.625ZM10 2.5l2.625 2.625L10 7.75 7.375 5.125 10 2.5ZM14.875 7.375 17.5 10l-2.625 2.625L12.25 10l2.625-2.625ZM10 12.25l2.625 2.625L10 17.5l-2.625-2.625L10 12.25Z"
      fill={color}
      stroke={color}
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);
const ForwardRef = forwardRef(ComponentSolid);
export default ForwardRef;
