/**
 * This file was generated automatically by the @perseus/generate-icons CLI.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../../types";
const ComputerDesktopSolid = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M1.875 4.375a2.5 2.5 0 0 1 2.5-2.5h11.25a2.5 2.5 0 0 1 2.5 2.5V12.5a2.5 2.5 0 0 1-2.5 2.5h-2.5v.214c0 .498.197.975.55 1.326l.517.518a.625.625 0 0 1-.442 1.067h-7.5a.625.625 0 0 1-.442-1.067l.518-.518c.351-.351.549-.828.549-1.325V15h-2.5a2.5 2.5 0 0 1-2.5-2.5V4.375Zm1.25 0v6.25a1.25 1.25 0 0 0 1.25 1.25h11.25a1.25 1.25 0 0 0 1.25-1.25v-6.25a1.25 1.25 0 0 0-1.25-1.25H4.375a1.25 1.25 0 0 0-1.25 1.25Z"
      fill={color}
    />
  </svg>
);
const ForwardRef = forwardRef(ComputerDesktopSolid);
export default ForwardRef;
