/**
 * This file was generated automatically by the @medusa-ui/generate-icons CLI.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../../types";
const DotsSix = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      d="M7.5 10.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5ZM7.5 5.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5ZM7.5 15.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5ZM12.5 10.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5ZM12.5 5.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5ZM12.5 15.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Z"
      stroke={color}
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);
const ForwardRef = forwardRef(DotsSix);
export default ForwardRef;
