/**
 * This file was generated automatically by @medusa-ui/cli.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../../types";
const EnvelopeSolid = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      d="M1.625 7.344v6.844a2.393 2.393 0 0 0 2.393 2.392h11.964a2.393 2.393 0 0 0 2.393-2.392V7.344l-7.121 4.381a2.393 2.393 0 0 1-2.508 0L1.625 7.344Z"
      fill={color}
    />
    <path
      d="M18.375 5.938v-.126a2.393 2.393 0 0 0-2.393-2.392H4.018a2.393 2.393 0 0 0-2.393 2.392v.126l7.748 4.769a1.196 1.196 0 0 0 1.254 0l7.748-4.769Z"
      fill={color}
    />
  </svg>
);
const ForwardRef = forwardRef(EnvelopeSolid);
export default ForwardRef;
