/**
 * This file was generated automatically by the @medusa-ui/generate-icons CLI.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../../types";
const Folder = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      d="M2.492 10.578V10a1.733 1.733 0 0 1 1.733-1.733h11.55A1.733 1.733 0 0 1 17.508 10v.578m-6.692-4.96L9.184 3.987a1.155 1.155 0 0 0-.817-.339H4.225A1.733 1.733 0 0 0 2.492 5.38v9.24a1.733 1.733 0 0 0 1.733 1.733h11.55a1.733 1.733 0 0 0 1.733-1.733V7.69a1.733 1.733 0 0 0-1.733-1.733h-4.142c-.306 0-.6-.122-.817-.338Z"
      stroke={color}
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);
const ForwardRef = forwardRef(Folder);
export default ForwardRef;
