/**
 * This file was generated automatically by the @medusa-ui/generate-icons CLI.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../../types";
const Heart = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      d="M17.5 6.875c0-2.07-1.75-3.75-3.907-3.75-1.612 0-2.997.938-3.593 2.277-.596-1.339-1.98-2.277-3.594-2.277-2.156 0-3.906 1.68-3.906 3.75 0 6.017 7.5 10 7.5 10s7.5-3.983 7.5-10Z"
      stroke={color}
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);
const ForwardRef = forwardRef(Heart);
export default ForwardRef;
