/**
 * This file was generated automatically by the @medusa-ui/generate-icons CLI.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../../types";
const LightBulb = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      d="M10 14.588v-4.015m0 0c.387 0 .773-.049 1.148-.145M10 10.573c-.387 0-.772-.049-1.147-.145m2.868 5.72a9.226 9.226 0 0 1-3.442 0m2.869 1.822c-.763.08-1.532.08-2.295 0m2.868-3.382v-.147c0-.752.504-1.394 1.154-1.771a5.736 5.736 0 1 0-5.75 0c.65.377 1.154 1.02 1.154 1.771v.147"
      stroke={color}
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);
const ForwardRef = forwardRef(LightBulb);
export default ForwardRef;
