/**
 * This file was generated automatically by @medusa-ui/cli.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../../types";
const Map = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      d="M7.5 5.625V12.5m5-5v6.875m.42 2.915 4.062-2.03a.937.937 0 0 0 .518-.84V4.018a.937.937 0 0 0-1.357-.839L12.92 4.79a.934.934 0 0 1-.838 0L7.919 2.71a.937.937 0 0 0-.838 0L3.018 4.74a.937.937 0 0 0-.518.84v10.403a.937.937 0 0 0 1.357.839L7.08 15.21a.934.934 0 0 1 .838 0l4.162 2.08a.939.939 0 0 0 .838 0v0Z"
      stroke={color}
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);
const ForwardRef = forwardRef(Map);
export default ForwardRef;
