/**
 * This file was generated automatically by the @medusa-ui/generate-icons CLI.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../../types";
const PaperClip = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      d="m17.084 9.532-6.698 6.688a4.378 4.378 0 0 1-6.188 0 4.366 4.366 0 0 1 0-6.179l6.698-6.688a2.92 2.92 0 0 1 4.98 2.06 2.91 2.91 0 0 1-.855 2.06L8.316 14.16a1.46 1.46 0 0 1-2.49-1.03c0-.386.154-.757.428-1.03L12.44 5.93"
      stroke={color}
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);
const ForwardRef = forwardRef(PaperClip);
export default ForwardRef;
