/**
 * This file was generated automatically by @medusa-ui/cli.
 * Do not edit this file directly.
 */
import * as React from "react"
import { Ref, forwardRef } from "react"
import type { IconProps } from "../../types"
const PlayMiniSolid = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>,
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M5 5.768a1.25 1.25 0 0 1 1.853-1.095l7.693 4.232a1.25 1.25 0 0 1 0 2.19l-7.693 4.232a1.25 1.25 0 0 1-1.852-1.095L5 5.768Z"
      fill={color}
    />
  </svg>
)
const ForwardRef = forwardRef(PlayMiniSolid)
export default ForwardRef
