/**
 * This file was generated automatically by @medusa-ui/cli.
 * Do not edit this file directly.
 */
import * as React from "react"
import { Ref, forwardRef } from "react"
import type { IconProps } from "../../types"
const TriangleDownMini = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>,
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M13.087 6.25c.693 0 1.133.75.799 1.363l-3.087 5.66a.908.908 0 0 1-1.598 0l-3.087-5.66C5.78 7 6.22 6.25 6.914 6.25h6.173Z"
      fill={color}
    />
  </svg>
)
const ForwardRef = forwardRef(TriangleDownMini)
export default ForwardRef
