/**
 * This file was generated automatically by the @perseus/generate-icons CLI.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../../types";
const TriangleRightMini = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M6.25 6.913c0-.693.75-1.133 1.363-.799l5.66 3.087a.908.908 0 0 1 0 1.598l-5.66 3.087c-.613.334-1.363-.106-1.363-.8V6.914Z"
      fill={color}
    />
  </svg>
);
const ForwardRef = forwardRef(TriangleRightMini);
export default ForwardRef;
