import Overview from "@/components/overview";
import { TestButton } from "@/components/TestButton/TestButton";
import { ThemeProvider } from "@medusa-ui/core";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider>
        <main className="bg-backgrounds-subtle text-text-primary p-8 flex flex-col items-center justify-center">
          <div>
            <h1 className="text-4xl font-bold">Medusa UI Icons</h1>
          </div>
          <Overview />
          <TestButton />
        </main>
      </ThemeProvider>
    </>
  );
}
