import Overview from "@/components/overview";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-backgrounds-subtle text-text-primary p-8 flex flex-col items-center justify-center">
        <div>
          <h1 className="text-4xl font-bold">Perseus Icons</h1>
        </div>
        <Overview />
      </main>
    </>
  );
}
