/**
 * This file was generated automatically by the @perseus/generate-icons CLI.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../../types";
const Az = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <g clipPath="url(#prefix__a)">
      <path d="M4.002 5.5h12v9h-12v-9Z" fill="#3F9C35" />
      <path d="M4.002 5.5h12v6h-12v-6Z" fill="#ED2939" />
      <path d="M4.002 5.5h12v3h-12v-3Z" fill="#00B9E4" />
      <path
        d="M9.7 11.35a1.35 1.35 0 1 0 0-2.7 1.35 1.35 0 0 0 0 2.7Z"
        fill="#fff"
      />
      <path
        d="M10 11.125a1.125 1.125 0 1 0 0-2.25 1.125 1.125 0 0 0 0 2.25Z"
        fill="#ED2939"
      />
      <path
        d="m11.2 9.25.144.403.387-.184-.184.389.403.142-.403.144.184.387-.387-.184-.144.403-.144-.403-.387.184.184-.387L10.45 10l.403-.144-.184-.387.387.184.144-.403Z"
        fill="#fff"
      />
    </g>
    <defs>
      <clipPath id="prefix__a">
        <rect x={4} y={5.5} width={12} height={9} rx={1} fill="#fff" />
      </clipPath>
    </defs>
  </svg>
);
const ForwardRef = forwardRef(Az);
export default ForwardRef;
