/**
 * This file was generated automatically by @medusa-ui/cli.
 * Do not edit this file directly.
 */
import * as React from "react"
import { Ref, forwardRef } from "react"
import type { IconProps } from "../../types"
const Bh = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>,
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <g clipPath="url(#prefix__a)" fillRule="evenodd" clipRule="evenodd">
      <path d="M3.39 5.5h13.5v9H3.39v-9Z" fill="#E10011" />
      <path
        d="m6.143 14.496-2.752.004v-9h2.737l1.768.57-1.753.553 1.753.572-1.753.553 1.753.572-1.753.553 1.753.572-1.753.553 1.753.572-1.753.553 1.753.572-1.753.553 1.753.572-1.753.553 1.753.572-1.753.553"
        fill="#fff"
      />
    </g>
    <defs>
      <clipPath id="prefix__a">
        <rect x={4} y={5.5} width={12} height={9} rx={1} fill="#fff" />
      </clipPath>
    </defs>
  </svg>
)
const ForwardRef = forwardRef(Bh)
export default ForwardRef
