/**
 * This file was generated automatically by @medusa-ui/cli.
 * Do not edit this file directly.
 */
import * as React from "react"
import { Ref, forwardRef } from "react"
import type { IconProps } from "../../types"
const Dk = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>,
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      d="M3.999 6.5a1 1 0 0 1 1-1h10.002a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1H4.999a1 1 0 0 1-1-1v-7Z"
      fill="#C8102E"
    />
    <path d="M7.856 5.5h1.287v9H7.856v-9Z" fill="#fff" />
    <path d="M3.999 9.357h12.002v1.287H3.999V9.357Z" fill="#fff" />
  </svg>
)
const ForwardRef = forwardRef(Dk)
export default ForwardRef
