/**
 * This file was generated automatically by the @medusa-ui/generate-icons CLI.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../../types";
const No = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      d="M4 6.5a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-7Z"
      fill="#ED2939"
    />
    <path d="M7.375 5.5h2.25v9h-2.25v-9Z" fill="#fff" />
    <path d="M4 8.875h12v2.25H4v-2.25Z" fill="#fff" />
    <path d="M7.938 5.5h1.125v9H7.938v-9Z" fill="#002664" />
    <path d="M4 9.438h12v1.124H4V9.438Z" fill="#002664" />
  </svg>
);
const ForwardRef = forwardRef(No);
export default ForwardRef;
