/**
 * This file was generated automatically by the @perseus/generate-icons CLI.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../types";
const AtSymbol = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      d="M13.75 10c0 1.38.84 2.5 1.875 2.5 1.036 0 1.875-1.12 1.875-2.5a7.5 7.5 0 1 0-2.197 5.303M13.75 10V6.875m0 3.125a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0v0Z"
      stroke={color}
      strokeWidth={1.5}
      strokeLinecap="round"
    />
  </svg>
);
const ForwardRef = forwardRef(AtSymbol);
export default ForwardRef;
