/**
 * This file was generated automatically by the @perseus/generate-icons CLI.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../types";
const Cog6Tooth = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      d="M7.995 3.283A.938.938 0 0 1 8.92 2.5h2.16c.46 0 .85.332.926.783l.177 1.068c.053.311.261.572.538.725.062.033.122.069.183.106.27.163.6.214.896.103l1.014-.38a.937.937 0 0 1 1.142.408l1.08 1.873a.937.937 0 0 1-.217 1.192l-.836.69c-.244.2-.365.51-.359.826.002.071.002.142 0 .213-.006.315.115.625.359.825l.837.69a.938.938 0 0 1 .217 1.191l-1.082 1.873a.938.938 0 0 1-1.14.409l-1.015-.38a1.039 1.039 0 0 0-.897.103c-.06.037-.121.073-.183.107a1.04 1.04 0 0 0-.537.724l-.177 1.067a.938.938 0 0 1-.925.784H8.919a.938.938 0 0 1-.925-.783l-.177-1.068a1.037 1.037 0 0 0-.537-.725 5.398 5.398 0 0 1-.183-.106c-.271-.163-.6-.214-.897-.103l-1.014.38a.938.938 0 0 1-1.14-.408l-1.082-1.873a.938.938 0 0 1 .217-1.192l.837-.69c.243-.2.364-.51.358-.826a5.788 5.788 0 0 1 0-.213 1.034 1.034 0 0 0-.358-.825l-.837-.69a.938.938 0 0 1-.217-1.191l1.081-1.873a.938.938 0 0 1 1.142-.409l1.013.38c.297.11.626.06.897-.103.06-.037.121-.073.183-.107.277-.152.485-.413.537-.724l.178-1.068v0Z"
      stroke={color}
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M12.5 10a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0v0Z"
      stroke={color}
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);
const ForwardRef = forwardRef(Cog6Tooth);
export default ForwardRef;
