/**
 * This file was generated automatically by the @perseus/generate-icons CLI.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../types";
const CurrencyDollar = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      d="M10 5v10m-2.5-2.348.732.549c.976.732 2.559.732 3.536 0 .976-.733.976-1.92 0-2.652C11.28 10.182 10.64 10 10 10c-.604 0-1.208-.183-1.67-.55-.92-.732-.92-1.918 0-2.65.922-.733 2.418-.733 3.34 0l.345.274M17.5 10a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0Z"
      stroke={color}
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);
const ForwardRef = forwardRef(CurrencyDollar);
export default ForwardRef;
