/**
 * This file was generated automatically by @medusa-ui/cli.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../../types";
const Facebook = (
  { color = "currentColor", ...props }: IconProps,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M1 10c0 4.455 3.24 8.145 7.515 8.91l.053-.044-.008-.001V12.52H6.31V10h2.25V8.02c0-2.25 1.44-3.51 3.51-3.51.63 0 1.35.09 1.98.18v2.295h-1.17c-1.08 0-1.35.54-1.35 1.26V10h2.385l-.405 2.52h-1.98v6.345l-.082.015.037.03C15.76 18.145 19 14.455 19 10c0-4.95-4.05-9-9-9s-9 4.05-9 9Z"
      fill={color}
    />
  </svg>
);
const ForwardRef = forwardRef(Facebook);
export default ForwardRef;
