
/**
 * This file is automatically generated.
 * Please do not change this file!
 */

export { default as AppleColor } from "./apple-color";
export { default as Apple } from "./apple";
export { default as DiscordColor } from "./discord-color";
export { default as Discord } from "./discord";
export { default as GithubColor } from "./github-color";
export { default as Github } from "./github";
export { default as GoogleColor } from "./google-color";
export { default as Google } from "./google";
export { default as KlarnaColor } from "./klarna-color";
export { default as Klarna } from "./klarna";
export { default as LinkedinColor } from "./linkedin-color";
export { default as Linkedin } from "./linkedin";
export { default as MedusaColor } from "./medusa-color";
export { default as Medusa } from "./medusa";
export { default as SlackColor } from "./slack-color";
export { default as Slack } from "./slack";
export { default as TwitterColor } from "./twitter-color";
export { default as Twitter } from "./twitter";
