/**
 * This file was generated automatically by the @perseus/generate-icons CLI.
 * Do not edit this file directly.
 */
import * as React from "react";
import { Ref, forwardRef } from "react";
import type { IconProps } from "../../types";
const KlarnaColor = (
  props: Omit<IconProps, "color">,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    width={20}
    height={20}
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={ref}
    {...props}
  >
    <path d="M10 19a9 9 0 1 0 0-18 9 9 0 0 0 0 18Z" fill="#FFB3C7" />
    <path
      d="M12.041 6.137h-1.64A4.159 4.159 0 0 1 8.723 9.49l-.641.476 2.492 3.397h2.045l-2.293-3.108a5.734 5.734 0 0 0 1.715-4.118ZM7.874 6.137H6.211v7.234h1.663V6.137Z"
      fill="#000"
    />
    <path
      d="M13.713 11.293a1.096 1.096 0 1 0-.001 2.191 1.096 1.096 0 0 0 .001-2.191Z"
      fill="#000"
    />
  </svg>
);
const ForwardRef = forwardRef(KlarnaColor);
export default ForwardRef;
